// Generated by https://quicktype.io

export interface ReferenceInterface {
  id:                number;
  title:             string;
  dateOfPublication: string;
  editorial:         null;
  publicationPlace:  null;
  note:              string;
  createAt:          string;
  referenceAuthor:   ReferenceAuthor[];
  referenceTag:      ReferenceTag[];
}

export interface ReferenceAuthor {
  id:       number;
  createAt: string;
  author:   Author;
}

export interface Author {
  id:       number;
  name:     string;
  createAt: string;
  color?:   string;
}

export interface ReferenceTag {
  id:       number;
  createAt: string;
  tag:      Author;
}
